apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epeagle-nginx-ing-tmp
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.DomainWebTmp }}
      secretName: epeagle-nginx-cert-tmp
  rules:
    - host: {{ .Values.DomainWebTmp }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: epeagle-epeagle-nginx
                port:
                  number: 80
