apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ing-1
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "true" #Wordpress will redirect to https internally
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  tls:
    - hosts:
      - {{ .Values.domainWordpress }}
      - www.{{ .Values.DomainWeb1 }}
      secretName: web-cert-1
  rules:
    - host: {{ .Values.DomainWeb1 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: epeagle-epeagle-nginx
                port:
                  number: 80
  
    - host: www.{{ .Values.DomainWeb1 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: epeagle-epeagle-nginx
                port:
                  number: 80
