
epeagle-php:
  enabled: true
  nameOverride: epeagle-php

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment

    image:
      name: asia-southeast3-docker.pkg.dev/its-artifact-commons/p2web/epeagle-php

  service:
    enabled: true
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: http
