mariadb:
  enabled: true
  fullnameOverride: mariadb
  auth:
    username: epeagle
    database: epeagle
    existingSecret: mariadb-secret

    #secretKeys:
    #  adminPasswordKey: adminPasswordKey

  image:
    repository: bitnamilegacy/mariadb

  global:
    security:
      allowInsecureImages: true

  primary:
    persistence:
      enabled: true
      size: 100Gi

    resources:
      requests:
        memory: "1Gi"
        cpu: "300m"
      limits:
        memory: "2Gi"
        cpu: "1"
