---
envAlias: development
envAliasJob: Development
envGroup: dev

DomainWebTmp: web-dev.epeagle-pharma.com
DomainWeb1: web-dev.epeagle-pharma.com
DomainWeb2: web-dev.ep-eagle-pharma.com
DomainWeb3: web-dev.epeaglepharma.com
